# Global
model_dir_path: ./resources/models/pre_trained
# use_auth_token: none  # Authentication token for HuggingFace models hub
# HuggingFace models
#models:
#  meta-llama-Llama-2-7b-hf: meta-llama/Llama-2-7b-hf
#  meta-llama-Llama-2-7b-chat-hf: meta-llama/Llama-2-7b-chat-hf
#Sentence transformers models
sentence_models:
  bienc:
    sentence-transformers-paraphrase-multilingual-mpnet-base-v2: paraphrase-multilingual-mpnet-base-v2
  xenc:
    amberoad-bert-multilingual-passage-reranking-msmarco: amberoad/bert-multilingual-passage-reranking-msmarco
# PyTorch weights checkpoints
#checkpoints:
#  TheBloke-Vicuna-13B-v-1-5-16K-GGUF:
#    # - https://huggingface.co/TheBloke/vicuna-13B-v1.5-16K-GGUF/resolve/main/vicuna-13b-v1.5-16k.Q4_K_M.gguf
#    - https://huggingface.co/TheBloke/vicuna-13B-v1.5-16K-GGUF/resolve/main/vicuna-13b-v1.5-16k.Q5_K_M.gguf
